Add migration to bigint columns
nextcloud/richdocuments pull request #1243
Opened 2020-11-12 12:05 UTC by juliushaertl

2020-11-12 12:09 UTC, rullzer approved these changes
Fine by me.
But there is also https://github.com/nextcloud/server/blob/2a054e6c04e0a40421510eb889cbf59f153c5177/lib/public/Migration/BigIntMigration.php#L34

2020-11-12 12:41 UTC, nickvergessen requested changes
Please use the repair step way instead.

2020-11-12 12:43 UTC, nickvergessen commented
Add it to https://github.com/nextcloud/server/blob/3f691c52dcced41aadf5e41b21856dd6bdd92fa0/core/Command/Db/ConvertFilecacheBigInt.php#L54-L75
it already contains apps anyway. Maybe it should be migrated to the way AddMissing* commands work, so apps can do it via hooks instead.

2020-11-12 13:40 UTC, MorrisJobke commented
> Please use the repair step way instead.

So the way to go is, that this change should be added to an existing migration. In that way it is already applied on new installations, but not triggered on existing installations (to not cause huge downtimes). Then we add something to the server.

2020-11-12 13:41 UTC, juliushaertl commented
> Maybe it should be migrated to the way AddMissing* commands work, so apps can do it via hooks instead.

I guess that makes sense, yes. Adding more hardcoded app tables to server doesn't seem right to me.

> So the way to go is, that this change should be added to an existing migration. In that way it is already applied on new installations, but not triggered on existing installations (to not cause huge downtimes). Then we add something to the server.

Sounds good :+1:

2020-11-13 10:31 UTC, juliushaertl commented
Added the migration as `occ richdocuments:convert-bigint` for now so we can get this out as a release.

For future enhancements we can move this to https://github.com/nextcloud/server/issues/24100 once it is there.

2020-11-13 14:22 UTC, nickvergessen commented on lib/Migration/Version2060Date20200302131958.php
>  				'length' => 4,
drop or 20?

2020-11-13 14:33 UTC, nickvergessen approved these changes

2020-11-13 14:50 UTC, merged