richdocuments: add host_session_id parameter
nextcloud/richdocuments pull request #3763
Opened 2024-06-13 22:11 UTC by hcvcastro

* Resolves: # 
* Target version: main

### Summary

### TODO

- [ ] ...

### Checklist

- [ ] Code is properly formatted
- [ ] Sign-off message is added to all commits
- [ ] Documentation (manuals or wiki) has been updated or is not required

2024-06-14 08:42 UTC, juliushaertl commented
Can you provide some context on what this is used?

In addition you can already get the richdocuments version in the frontend code through the capabilities so no backend changes should be required and please also add it to https://github.com/nextcloud/richdocuments/blob/e9ec3189c92c229475f6430b47e02d6463699c65/src/view/Office.vue#L51
```
import { getCapabilities } from '../services/capabilities.ts'

getCapabilities().version
```

2024-06-14 08:42 UTC, juliushaertl requested changes
Needs mentioned adjustments

2024-06-14 11:40 UTC, hcvcastro commented
Thanks, it is mostly to implement Wopi HOST_SESSION_ID, to debugging log purposes and
to track wopi host  logs for troubleshooting purposes based on a host-specific session identifier

2024-06-14 12:03 UTC, juliushaertl commented on src/document.js
> +import { getCapabilities } from '../services/capabilities.ts'
```suggestion
import { getCapabilities } from './services/capabilities.ts'
```

2024-06-26 14:58 UTC, juliushaertl requested changes
Still needs to also be added in 
https://github.com/nextcloud/richdocuments/blob/e9ec3189c92c229475f6430b47e02d6463699c65/src/view/Office.vue#L51

2024-07-15 11:09 UTC, merged